### ISSUE TITLE
Program To Rotate An Array in Anticlockwise direction in c++

### ISSUE THREAD

**Issue by KratikJain10** [shravan2524/hacktoberfest#26]
Hello. @shravan2524 
myself kratik.
I want to add a C++ program to rotate an array in anticlockwise direction. I am new to open source and looking forward to complete hacktoberfest by making this contribution.
Kindly assign me this issue.
Thank You,
#hactoberfest2022

**Comment by Brainskull24** [comment]
Can you pls assign this issue to me @shravan2524 ?
