### ISSUE TITLE
Palindroam program

### ISSUE THREAD

**Issue by shravan2524** [shravan2524/hacktoberfest#3]
Given a string check whether it is a palindroam or not in c++.

input : aabbaa
output :  palindroam

input : aabbaaa
output :  Not a palindroam

**Comment by Teddy1404** [comment]
assign me please

**Comment by Revathi-80** [comment]
Hey, @shravan2524 can you please assign this issue to me?

**Comment by shravanc26** [comment]
hey, @shravanc26 can you pls assign this problem to me
thanks :)

**Comment by shravan2524** [comment]
it's done.
