### ISSUE TITLE
Sum of number

### ISSUE THREAD

**Issue by shravan2524** [shravan2524/hacktoberfest#5]
Count sum of a number

Input : 124
ouput : 7 (1+2+4)

**Comment by harsitagarwalla187** [comment]
Can i work in this issue?

**Comment by Soumyajit2825** [comment]
@shravan2524 please assign me to this issue

**Comment by Revathi-80** [comment]
Hey, @shravan2524 can you please assign this issue to me?

**Comment by shravanc26** [comment]
Can you please assign me, So that I can work on this issue .: )

**Comment by shravan2524** [comment]
It's done
