### ISSUE TITLE
Reverse a number

### ISSUE THREAD

**Issue by shravan2524** [shravan2524/hacktoberfest#6]
reverse a number . take input as a integer.

input : 104
output : 401

**Comment by Samarthasbhat** [comment]
I will solve the problem

**Comment by Samarthasbhat** [comment]
I have added the program @shravan2524

**Comment by harsitagarwalla187** [comment]
Can you aasign me the issue?

**Comment by paras3624** [comment]
Hey! Can I contribute to this issue?

**Comment by shravanc26** [comment]
Hey, Can I do. please assign to me

**Comment by shravan2524** [comment]
it's close
